stages:
  - build
  - deploy
  - clean
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - build/
build_app:
  stage: build
  script:
    - npm install
    - unset CI
    - npm run build
copy_to_nginx:
  stage: deploy
  script:
    - cp -rf ./build/* /var/www/website
creare_artifact:
  stage: deploy
  script:
    - tar czf build.tar.gz ./build/
  artifacts:
    paths:
      - build.tar.gz
    expire_in: 3 day
remove:
  stage: clean
  script:
    - rm -rf ./build*
